export type ResultStoreDto = {
    id: number,
    name: string,
    email?: string,
    description: string,
    reference: string,
    logo: string,
    address: string,
    country: string,
    city: string,
    zipCode?: string,
    phoneNumber: string,
    callingCode: string,
    website?: string,
    createdAt: string,
    updatedAt: string,
    status: boolean,
    userId: number,
}